export interface BL {
  id: string;
  bl_code: string;
  naviera_id: string;
  fecha_bl: Date | undefined;
  revisado_con_exito: boolean;
  etapa: string;
  nave: string;
  manual_pendiente: boolean;
  id_carga: string;
  no_revisar: boolean;
  state_code: number;
  html_descargado: boolean;
  proxima_revision: Date;
  revisado_hoy: boolean;
  mercado: string;
}

export const mockBLs: BL[] = [
  {
    id: '1',
    bl_code: 'MAEU123456789',
    naviera_id: '1', // Maersk
    fecha_bl: new Date('2024-03-01'),
    revisado_con_exito: true,
    etapa: 'En tránsito',
    nave: 'Maersk Semarang',
    manual_pendiente: false,
    id_carga: 'CARGO123',
    no_revisar: false,
    state_code: 1,
    html_descargado: true,
    proxima_revision: new Date('2024-03-05'),
    revisado_hoy: true,
    mercado: 'asia',
  },
  {
    id: '2',
    bl_code: 'MSCU987654321',
    naviera_id: '2', // MSC
    fecha_bl: new Date('2024-02-28'),
    revisado_con_exito: true,
    etapa: 'Descargado',
    nave: 'MSC Oscar',
    manual_pendiente: false,
    id_carga: 'CARGO456',
    no_revisar: false,
    state_code: 2,
    html_descargado: true,
    proxima_revision: new Date('2024-03-06'),
    revisado_hoy: true,
    mercado: 'europe',
  },
  {
    id: '3',
    bl_code: 'CMAU456789123',
    naviera_id: '3', // CMA CGM
    fecha_bl: new Date('2024-02-25'),
    revisado_con_exito: false,
    etapa: 'Pendiente',
    nave: 'CMA CGM Marco Polo',
    manual_pendiente: true,
    id_carga: 'CARGO789',
    no_revisar: false,
    state_code: 3,
    html_descargado: false,
    proxima_revision: new Date('2024-03-04'),
    revisado_hoy: false,
    mercado: 'americas',
  },
  {
    id: '4',
    bl_code: 'HLCU112233445',
    naviera_id: '4', // Hapag-Lloyd
    fecha_bl: new Date('2024-03-02'),
    revisado_con_exito: true,
    etapa: 'En tránsito',
    nave: 'Hapag-Lloyd New York',
    manual_pendiente: false,
    id_carga: 'CARGO101',
    no_revisar: false,
    state_code: 1,
    html_descargado: true,
    proxima_revision: new Date('2024-03-07'),
    revisado_hoy: true,
    mercado: 'asia',
  },
  {
    id: '5',
    bl_code: 'ONEU667788990',
    naviera_id: '5', // ONE
    fecha_bl: new Date('2024-02-27'),
    revisado_con_exito: false,
    etapa: 'Pendiente',
    nave: 'ONE Osaka',
    manual_pendiente: true,
    id_carga: 'CARGO202',
    no_revisar: false,
    state_code: 3,
    html_descargado: false,
    proxima_revision: new Date('2024-03-08'),
    revisado_hoy: false,
    mercado: 'americas',
  },
  {
    id: '6',
    bl_code: 'COSU778899001',
    naviera_id: '6', // COSCO
    fecha_bl: new Date('2024-03-03'),
    revisado_con_exito: true,
    etapa: 'Descargado',
    nave: 'COSCO Beijing',
    manual_pendiente: false,
    id_carga: 'CARGO303',
    no_revisar: true,
    state_code: 2,
    html_descargado: true,
    proxima_revision: new Date('2024-03-09'),
    revisado_hoy: true,
    mercado: 'europe',
  },
  {
    id: '7',
    bl_code: 'EMCU334455667',
    naviera_id: '7', // Evergreen
    fecha_bl: new Date('2024-02-26'),
    revisado_con_exito: false,
    etapa: 'Pendiente',
    nave: 'Evergreen Shanghai',
    manual_pendiente: true,
    id_carga: 'CARGO404',
    no_revisar: false,
    state_code: 3,
    html_descargado: false,
    proxima_revision: new Date('2024-03-10'),
    revisado_hoy: false,
    mercado: 'asia',
  },
  {
    id: '8',
    bl_code: 'APL5678901234',
    naviera_id: '8', // APL
    fecha_bl: new Date('2024-03-01'),
    revisado_con_exito: true,
    etapa: 'En tránsito',
    nave: 'APL Paris',
    manual_pendiente: false,
    id_carga: 'CARGO505',
    no_revisar: false,
    state_code: 1,
    html_descargado: true,
    proxima_revision: new Date('2024-03-11'),
    revisado_hoy: true,
    mercado: 'europe',
  },
  {
    id: '9',
    bl_code: 'ZIM3456789012',
    naviera_id: '9', // ZIM
    fecha_bl: new Date('2024-02-24'),
    revisado_con_exito: false,
    etapa: 'Pendiente',
    nave: 'ZIM Haifa',
    manual_pendiente: true,
    id_carga: 'CARGO606',
    no_revisar: false,
    state_code: 3,
    html_descargado: false,
    proxima_revision: new Date('2024-03-12'),
    revisado_hoy: false,
    mercado: 'americas',
  },
  {
    id: '10',
    bl_code: 'OOCL2233445566',
    naviera_id: '10', // OOCL
    fecha_bl: new Date('2024-03-04'),
    revisado_con_exito: true,
    etapa: 'Descargado',
    nave: 'OOCL Rotterdam',
    manual_pendiente: false,
    id_carga: 'CARGO707',
    no_revisar: false,
    state_code: 2,
    html_descargado: true,
    proxima_revision: new Date('2024-03-13'),
    revisado_hoy: true,
    mercado: 'asia',
  },
  {
    id: '11',
    bl_code: 'NYKU7788991122',
    naviera_id: '11', // NYK Line
    fecha_bl: new Date('2024-02-23'),
    revisado_con_exito: false,
    etapa: 'Pendiente',
    nave: 'NYK Venus',
    manual_pendiente: true,
    id_carga: 'CARGO808',
    no_revisar: false,
    state_code: 3,
    html_descargado: false,
    proxima_revision: new Date('2024-03-14'),
    revisado_hoy: false,
    mercado: 'europe',
  },
  {
    id: '12',
    bl_code: 'KMTC0011223344',
    naviera_id: '12', // KMTC
    fecha_bl: new Date('2024-03-05'),
    revisado_con_exito: true,
    etapa: 'En tránsito',
    nave: 'KMTC Seoul',
    manual_pendiente: false,
    id_carga: 'CARGO909',
    no_revisar: false,
    state_code: 1,
    html_descargado: true,
    proxima_revision: new Date('2024-03-15'),
    revisado_hoy: true,
    mercado: 'americas',
  },
  {
    id: '13',
    bl_code: 'PIL9988776655',
    naviera_id: '13', // PIL
    fecha_bl: new Date('2024-02-22'),
    revisado_con_exito: false,
    etapa: 'Pendiente',
    nave: 'PIL Jakarta',
    manual_pendiente: true,
    id_carga: 'CARGO010',
    no_revisar: false,
    state_code: 3,
    html_descargado: false,
    proxima_revision: new Date('2024-03-16'),
    revisado_hoy: false,
    mercado: 'asia',
  },
  {
    id: '14',
    bl_code: 'MCCU8899776655',
    naviera_id: '14', // MCC Transport
    fecha_bl: new Date('2024-03-06'),
    revisado_con_exito: true,
    etapa: 'Descargado',
    nave: 'MCC Hanoi',
    manual_pendiente: false,
    id_carga: 'CARGO011',
    no_revisar: true,
    state_code: 2,
    html_descargado: true,
    proxima_revision: new Date('2024-03-17'),
    revisado_hoy: true,
    mercado: 'europe',
  },
  {
    id: '15',
    bl_code: 'SMLine9871236540',
    naviera_id: '15', // SM Line
    fecha_bl: new Date('2024-03-07'),
    revisado_con_exito: true,
    etapa: 'En tránsito',
    nave: 'SM Long Beach',
    manual_pendiente: false,
    id_carga: 'CARGO012',
    no_revisar: false,
    state_code: 1,
    html_descargado: true,
    proxima_revision: new Date('2024-03-18'),
    revisado_hoy: true,
    mercado: 'americas',
  },
];
